# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'knowme' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for knowme

  target 'knowmeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'Firebase/Core'
pod 'React', :path => '../node_modules/react-native'
pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
pod 'React', path: '../node_modules/react-native', subspecs: [
  'ART',
]